# apiVersion: v1
# kind: Service
# metadata:
#   name: sample-app
#   namespace: default
# spec:
#   type: LoadBalancer # In Minikube this might need 'minikube tunnel' or NodePort
#   selector:
#     app: sample-app
#   ports:
#   - port: 80
#     targetPort: 8080
#     protocol: TCP
